import { isFileError, parseLocaleText } from './parse';
import type { FileError, LoadedLocale } from './types';

/**
 * The standard texts live in `public/locales`, so the app can start without
 * anyone uploading anything. `manifest.json` lists what is actually there —
 * generated by `node scripts/prepare-locales.mjs <folder>`.
 */
export const STANDARD_DIR = '/locales';

export interface ManifestEntry {
  code: string;
  file: string;
  keys?: number;
}

export interface LocaleManifest {
  generatedAt?: string;
  locales: ManifestEntry[];
}

/** Returns null when there are no standard files yet — never throws. */
export async function loadManifest(): Promise<LocaleManifest | null> {
  try {
    const response = await fetch(`${STANDARD_DIR}/manifest.json`, { cache: 'no-store' });
    if (!response.ok) return null;
    const parsed = (await response.json()) as unknown;
    if (typeof parsed !== 'object' || parsed === null || !Array.isArray((parsed as LocaleManifest).locales)) {
      return null;
    }
    const locales = (parsed as LocaleManifest).locales.filter(
      (entry) => typeof entry?.code === 'string' && typeof entry?.file === 'string',
    );
    return locales.length ? { ...(parsed as LocaleManifest), locales } : null;
  } catch {
    return null;
  }
}

export async function fetchStandardLocale(entry: ManifestEntry): Promise<LoadedLocale | FileError> {
  let text: string;
  try {
    const response = await fetch(`${STANDARD_DIR}/${entry.file}`, { cache: 'no-store' });
    if (!response.ok) {
      return {
        fileName: entry.file,
        message: `Listed in the manifest but missing from public/locales (${response.status}). Run the prepare script again.`,
      };
    }
    text = await response.text();
  } catch {
    return { fileName: entry.file, message: 'Could not be read from public/locales.' };
  }

  const result = parseLocaleText(text, entry.file, entry.code, 'standard');
  if (isFileError(result)) return result;
  return result;
}
